#!/usr/bin/env python3

import math
import sys
import time

def f(x, u, o):
    a = 2 * math.pi
    b = math.sqrt(a)
    c = 1 / (o * b)
    d = (x - u) ** 2
    e = 2 * (o ** 2)
    f = - (d / e)
    g = math.exp(f)
    h = c * g
    return (h)

def iq(u, o):
    i = 0
    tab = []
    while (i < 201):
        tab.append(f(i, u, o))
        i += 1
    return (tab)

def print_tab(tab):
    i = 0
    while (i < 201):
        print("%d %.5f" %(i, tab[i]))
        i += 1

if (__name__ == "__main__"):
    try:
        u = int(sys.argv[1])
        o = int(sys.argv[2])
        if (u < 0 or u > 200 or o < 0):
            sys.exit(84)
        tab = iq(u, o)
    except:
        sys.exit(84)

    if (len(sys.argv) == 3):
        print_tab(tab);
        sys.exit(0)
    elif (len(sys.argv) == 4):
        try:
            maxi = int(sys.argv[3])
        except:
            sys.exit(84)

        if (maxi < 0):
            sys.exit(84)

        i = 0.0
        perc = 0.0
        while (i < maxi):
            perc += f(i, u, o)
            i += 0.01
        print("%.1f%% of people have an IQ inferior to %d" %(perc, maxi))
        sys.exit(0)
    elif (len(sys.argv) == 5):

        try:
            i = int(sys.argv[3])
        except:
            sys.exit(84)

        mini = i

        try:
            maxi = int(sys.argv[4])
        except:
            sys.exit(84)

        if (maxi < 0 or mini < 0 or maxi < mini):
            sys.exit(84)

        perc = 0.0
        while (i < maxi):
            perc += f(i, u, o)
            i += 0.01
        print("%.1f%% of people have an IQ between %d and %d" %(perc, mini, maxi))
        sys.exit(0)
    else:
        sys.exit(84)
