#!/usr/bin/env python3

import math
import sys

def set_max(val):
    if (val > 100):
        print("100.00", end='')
    else:
        print("%0.2f" % val, end='')

def set_min(val):
    if (val < 0):
        print("0.00", end='')
    else:
        print("%0.2f" % val, end='')

if (__name__ == "__main__"):
    try:
        if (len(sys.argv) != 4):
            sys.exit(84)
        size = int(sys.argv[1])
        echantillon = int(sys.argv[2])
        perc = float(sys.argv[3])

        if (size < 2 or size < echantillon or echantillon < 0):
            sys.exit(84)
        if (perc < 0 or perc > 100):
            sys.exit(84)

        p = perc / 100
        variance = ((p * (1 - p)) / echantillon) * ((size - echantillon) / (size - 1))

        conf95 = 1.96 * math.sqrt(variance)
        conf99 = 2.58 * math.sqrt(variance)
        print("Population size:\t %d" %size)
        print("Sample size:\t\t %d" %echantillon)
        print("Voting intentions:\t %.2f" %perc)
        print("Variance:\t\t %.6f" %variance)
        print("95% confidence interval: [", end='')
        set_min(perc - conf95 * 100)
        print("%; ", end='')
        set_max(perc + conf95 * 100)
        print("%]")
        print("99% confidence interval: [", end='')
        set_min(perc - conf99 * 100)
        print("%; ", end='')
        set_max(perc + conf99 * 100)
        print("%]")
    except:
        sys.exit(84)
    sys.exit(0)
